import { createContext, useState } from 'react';

const translations = {
    en: {
        appName: 'SocketSupport',
        login: 'Log in',
        register: 'Create account',
        username: 'Username',
        password: 'Password',
        role: 'Role',
        student: 'Student',
        agent: 'Agent',
        noAccount: 'No account?',
        hasAccount: 'Have an account?',
        settings: 'Settings',
        logout: 'Log out',
        dashboard: 'Dashboard',
        newTicket: 'New ticket',
        subject: 'Subject',
        urgency: 'Urgency',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
        create: 'Create',
        cancel: 'Cancel',
        myTickets: 'My tickets',
        openTickets: 'Open tickets',
        claim: 'Claim',
        resolve: 'Resolve',
        send: 'Send',
        typeMessage: 'Type a message...',
        selectTicket: 'Select a ticket to view the conversation',
        noTickets: 'No tickets yet',
        typing: 'is typing...',
        loadOlder: 'Load older messages',
        appearance: 'Appearance',
        theme: 'Theme',
        dark: 'Dark',
        light: 'Light',
        fontSize: 'Font size',
        small: 'Small',
        large: 'Large',
        language: 'Language',
        changePassword: 'Change password',
        currentPassword: 'Current password',
        newPassword: 'New password',
        updatePassword: 'Update password',
        avatar: 'Avatar',
        upload: 'Upload',
        saveSettings: 'Save preferences',
        back: 'Back',
        open: 'Open',
        active: 'Active',
        resolved: 'Resolved',
        heroTitle: 'Resolve issues faster than ever before.',
        heroSubtitle: 'A premium ticketing and live chat system designed for modern teams. Support your users instantly with persistent, multi-language WebSocket connections.',
        getStarted: 'Get Started',
        agentLogin: 'Agent Login',
        f1Title: 'Lightning Fast',
        f1Desc: 'Powered by Socket.io for zero-latency messaging.',
        f2Title: 'Secure Roles',
        f2Desc: 'Strict boundaries between student requests and agent dashboards.',
        f3Title: 'Multi-lingual',
        f3Desc: 'Instant localization into English, French, and German.',
        lowDesc: 'Low (General)',
        mediumDesc: 'Medium (Account)',
        highDesc: 'High (Blocker)',
        attachFile: 'Attach file',
        uploading: 'Uploading...',
        emoji: 'Emoji',
        attachment: 'Attachment',
        backToTickets: 'Back to tickets',
        fileTooLarge: 'File exceeds the 5MB limit.',
        createStudentAccount: 'Create a student account',
        joinPlatform: 'Join the platform.',
        registerDesc: 'Create a student account to get instant help.',
    },
    fr: {
        appName: 'SocketSupport',
        login: 'Connexion',
        register: 'Creer un compte',
        username: "Nom d'utilisateur",
        password: 'Mot de passe',
        role: 'Role',
        student: 'Etudiant',
        agent: 'Agent',
        noAccount: 'Pas de compte ?',
        hasAccount: 'Deja un compte ?',
        settings: 'Parametres',
        logout: 'Deconnexion',
        dashboard: 'Tableau de bord',
        newTicket: 'Nouveau ticket',
        subject: 'Sujet',
        urgency: 'Urgence',
        low: 'Faible',
        medium: 'Moyen',
        high: 'Eleve',
        create: 'Creer',
        cancel: 'Annuler',
        myTickets: 'Mes tickets',
        openTickets: 'Tickets ouverts',
        claim: 'Prendre en charge',
        resolve: 'Resoudre',
        send: 'Envoyer',
        typeMessage: 'Ecrivez un message...',
        selectTicket: 'Selectionnez un ticket pour voir la conversation',
        noTickets: 'Aucun ticket',
        typing: 'est en train de taper...',
        loadOlder: 'Charger les anciens messages',
        appearance: 'Apparence',
        theme: 'Theme',
        dark: 'Sombre',
        light: 'Clair',
        fontSize: 'Taille de police',
        small: 'Petit',
        large: 'Grand',
        language: 'Langue',
        changePassword: 'Changer le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        updatePassword: 'Mettre a jour',
        avatar: 'Avatar',
        upload: 'Telecharger',
        saveSettings: 'Enregistrer',
        back: 'Retour',
        open: 'Ouvert',
        active: 'Actif',
        resolved: 'Resolu',
        heroTitle: 'Resolvez les problemes plus rapidement que jamais.',
        heroSubtitle: 'Un systeme de billetterie et de chat en direct premium concu pour les equipes modernes. Soutenez vos utilisateurs instantanement.',
        getStarted: 'Commencer',
        agentLogin: 'Connexion Agent',
        f1Title: 'Ultra Rapide',
        f1Desc: 'Propulse par Socket.io pour une messagerie sans latence.',
        f2Title: 'Roles Securises',
        f2Desc: 'Frontieres strictes entre les demandes des etudiants et le tableau de bord des agents.',
        f3Title: 'Multilingue',
        f3Desc: 'Localisation instantanee en anglais, francais et allemand.',
        lowDesc: 'Faible (General)',
        mediumDesc: 'Moyen (Compte)',
        highDesc: 'Eleve (Bloquant)',
        attachFile: 'Joindre un fichier',
        uploading: 'Telechargement...',
        emoji: 'Emoji',
        attachment: 'Piece jointe',
        backToTickets: 'Retour aux tickets',
        fileTooLarge: 'Le fichier depasse la limite de 5 Mo.',
        createStudentAccount: 'Creer un compte etudiant',
        joinPlatform: 'Rejoignez la plateforme.',
        registerDesc: 'Creez un compte etudiant pour obtenir une aide instantanee.',
    },
    de: {
        appName: 'SocketSupport',
        login: 'Anmelden',
        register: 'Konto erstellen',
        username: 'Benutzername',
        password: 'Kennwort',
        role: 'Rolle',
        student: 'Student',
        agent: 'Agent',
        noAccount: 'Kein Konto?',
        hasAccount: 'Bereits ein Konto?',
        settings: 'Einstellungen',
        logout: 'Abmelden',
        dashboard: 'Dashboard',
        newTicket: 'Neues Ticket',
        subject: 'Betreff',
        urgency: 'Dringlichkeit',
        low: 'Niedrig',
        medium: 'Mittel',
        high: 'Hoch',
        create: 'Erstellen',
        cancel: 'Abbrechen',
        myTickets: 'Meine Tickets',
        openTickets: 'Offene Tickets',
        claim: 'Ubernehmen',
        resolve: 'Loesen',
        send: 'Senden',
        typeMessage: 'Nachricht schreiben...',
        selectTicket: 'Ticket auswaehlen, um die Unterhaltung anzuzeigen',
        noTickets: 'Keine Tickets',
        typing: 'tippt...',
        loadOlder: 'Aeltere Nachrichten laden',
        appearance: 'Darstellung',
        theme: 'Design',
        dark: 'Dunkel',
        light: 'Hell',
        fontSize: 'Schriftgroesse',
        small: 'Klein',
        large: 'Gross',
        language: 'Sprache',
        changePassword: 'Kennwort aendern',
        currentPassword: 'Aktuelles Kennwort',
        newPassword: 'Neues Kennwort',
        updatePassword: 'Aktualisieren',
        avatar: 'Profilbild',
        upload: 'Hochladen',
        saveSettings: 'Speichern',
        back: 'Zurueck',
        open: 'Offen',
        active: 'Aktiv',
        resolved: 'Geloest',
        heroTitle: 'Loesen Sie Probleme schneller als je zuvor.',
        heroSubtitle: 'Ein Premium-Ticketing- und Live-Chat-System fuer moderne Teams. Unterstuetzen Sie Ihre Benutzer sofort.',
        getStarted: 'Loslegen',
        agentLogin: 'Agenten-Login',
        f1Title: 'Blitzschnell',
        f1Desc: 'Unterstuetzt durch Socket.io fuer Nachrichtenuebermittlung ohne Latenz.',
        f2Title: 'Sichere Rollen',
        f2Desc: 'Strikte Grenzen zwischen Studenten-Anfragen und Agenten-Dashboards.',
        f3Title: 'Mehrsprachig',
        f3Desc: 'Sofortige Lokalisierung in Englisch, Franzoesisch und Deutsch.',
        lowDesc: 'Niedrig (Allgemein)',
        mediumDesc: 'Mittel (Konto)',
        highDesc: 'Hoch (Blocker)',
        attachFile: 'Datei anhaengen',
        uploading: 'Wird hochgeladen...',
        emoji: 'Emoji',
        attachment: 'Anhang',
        backToTickets: 'Zurueck zu den Tickets',
        fileTooLarge: 'Die Datei ueberschreitet das 5-MB-Limit.',
        createStudentAccount: 'Studentenkonto erstellen',
        joinPlatform: 'Treten Sie der Plattform bei.',
        registerDesc: 'Erstellen Sie ein Studentenkonto, um sofortige Hilfe zu erhalten.',
    },
};

export const LanguageContext = createContext();

export function LanguageProvider({ children, initialLanguage }) {
    const [language, setLanguage] = useState(initialLanguage || 'en');
    const t = (key) => translations[language]?.[key] || key;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
